# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(539, 196)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Start.setGeometry(QtCore.QRect(440, 120, 81, 25))
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 491, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_CPFolder = QtWidgets.QLabel(self.layoutWidget)
        self.label_CPFolder.setObjectName("label_CPFolder")
        self.horizontalLayout.addWidget(self.label_CPFolder)
        self.lineEdit_CPFolder = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_CPFolder.setObjectName("lineEdit_CPFolder")
        self.horizontalLayout.addWidget(self.lineEdit_CPFolder)
        self.pushButton_CPFolder = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_CPFolder.setObjectName("pushButton_CPFolder")
        self.horizontalLayout.addWidget(self.pushButton_CPFolder)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 70, 401, 27))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_OutputName = QtWidgets.QLabel(self.layoutWidget1)
        self.label_OutputName.setObjectName("label_OutputName")
        self.horizontalLayout_2.addWidget(self.label_OutputName)
        self.lineEdit_OutputName = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_OutputName.setObjectName("lineEdit_OutputName")
        self.horizontalLayout_2.addWidget(self.lineEdit_OutputName)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 539, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Start.setText(_translate("MainWindow", "Start"))
        self.label_CPFolder.setText(_translate("MainWindow", "CP Folder:"))
        self.pushButton_CPFolder.setText(_translate("MainWindow", "Choose"))
        self.label_OutputName.setText(_translate("MainWindow", "OutputName:"))
        self.lineEdit_OutputName.setText(_translate("MainWindow", "Result_.csv"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
